apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Production release
        - $patch: replace
        image: image-registry.openshift-image-registry.svc:5000/reversewords-ci/reversewords:5bb697345323be0f3a5da5ed56e9d9771a87e9b6
        name: reverse-words
